### PR TITLE
Tops app revised

### PR DESCRIPTION
**Pull request by EJFielding**
added code to better use netrc if present

### CODE REVIEW

**Comment by EJFielding** [comment]
This also includes changes from #20

**Comment by EJFielding** [comment]
@yunjunz My old changes in this PR conflict with the ones in #22 by @nabolfat. How do I remove those commits from this PR?

**Comment by yunjunz** [comment]
> @yunjunz My old changes in this PR conflict with the ones in #22 by @nabolfat. How do I remove those commits from this PR?

The easy way would be to wait for #22 to get merged. Then rebase this PR against the `upstream/main` branch.

**Comment by EJFielding** [comment]
@yunjunz Thanks! I merged @nabolfat PR, pulled the upstream version, and then resolved all the conflicts. I think this PR is ready to merge.

**Comment by yunjunz** [comment]
@EJFielding there are other conflicts between this PR and #24. Could you resolve them?

**Comment by EJFielding** [comment]
I think I fixed the conflict (only a kernel choice).

**Comment by yunjunz** [comment]
hmm... The changes in these two PR now look the same to me. Although GitHub does not flag any issue, do you mind rebasing this PR against the latest `parosen/main` branch, to make sure that we are not merging the same thing twice? I don't know what would happen if that is the case.
+ https://app.reviewnb.com/parosen/Geo-SInC/pull/23/
+ https://app.reviewnb.com/parosen/Geo-SInC/pull/24/

**Comment by EJFielding** [comment]
I think you are right that the PR #24 had all the changes from #23. There were a few tiny differences in the notebook metadata about the selected kernel.

**Comment by EJFielding** [comment]
Maybe we can close this one. My use of the git branches was probably incorrect.

**Pull request closed without merging**
