### PR TITLE
changed file extension of corrupt notebook file

### PR DESCRIPTION
**Pull request by stevejpurves**
Hi, someone recently used this repository URL on the https://try.curvenote.com service, which threw an error.

Turns out that this notebook `UNAVCO2021/0.9_SAR_Imaging_Theory/SAR_Processor.ipynb`  is corrupt and cannot be opened. 

I have changed the file extension of the notebook in this PR, so it is ignored and the service now builds a website. The result is of that build is here: https://launchpad-xsx4mkxn95cw.curve.space/Geo-SInC (will expire in 5 days)

Note that the website was built based on the folder structure in this repo, it is possible to significantly improve the layout & table of contents by using the [curvenote CLI tool](https://curvenote.com/docs/web) and a little customization. If you are interested in that, I'm happy to open a further PR with that set up for you 🙂

### CODE REVIEW

**Review by EJFielding — CHANGES_REQUESTED** [review]
Hello, thanks for your PR. The commit that caused the notebook to become unreadable was reverted and merged yesterday, so this renaming is no longer necessary.

**Comment by stevejpurves** [comment]
Hi @EJFielding - I see did it make it into `main`? are the SAR_Processor notebook in `UNAVCO2021` still fails to render on github e.g. https://github.com/parosen/Geo-SInC/blob/main/UNAVCO2021/0.9_SAR_Imaging_Theory/SAR_Processor.ipynb

**Comment by EJFielding** [comment]
It opens when I use this path:
https://github.com/parosen/Geo-SInC/blob/main/UNAVCO2022/0.9_SAR_Imaging_Theory/SAR_Processor.ipynb

**Comment by EJFielding** [comment]
@stevejpurves Oh, now I see you are looking at the UNAVCO2021 notebook. That is corrupted. @yunjunz

**Comment by parosen** [comment]
At the moment, the notebook for 2021 should be the same as 2022.  So the fix is to update the repository be replacing the 2021 notebook with a copy of the 2022 notebook.  I can then make the appropriate equation fixes for the 2022 notebook that kicked off this whole mess!

**Comment by stevejpurves** [comment]
I'll go ahead and close this PR as #59 will resolve this.
Glad it got tracked down

**Pull request closed without merging**
