### PR TITLE
Minor code cell fixes, changed default kernel

### PR DESCRIPTION
**Pull request by geniusinaction**

### CODE REVIEW

**Review by EJFielding — APPROVED** [review]
looks good to me

**Comment by geniusinaction** [comment]
Merging!

**Comment by EJFielding** [comment]
Did you mean to remove the azimuth and incidence angle values from the 3D notebook?

**Comment by geniusinaction** [comment]
Yes, otherwise people would just click through. The information is in the
notebook for users to find.

Gareth

--
Gareth J Funning (he/him), Professor and Undergraduate Advisor
Department of Earth and Planetary Sciences, University of California,
Riverside, CA 92521, http://www.garethfunning.com/
<http://faculty.ucr.edu/~gareth>

**Pull request merged**
