### PR TITLE
update `.gitignore` file

### PR DESCRIPTION
**Pull request by EJFielding**
Updated the text to specify that stripmapApp is ISCE2 and added mention of NISAR with ISCE3.
Notebook changes were merged in #100. 
Additional change to `.gitignore` here.

### CODE REVIEW

**Comment by yunjunz** [comment]
@EJFielding The change of this PR currently shows a modification of the `.gitignore` file only, without the changes you mentioned in the PR description. Could you confirm?

**Comment by EJFielding** [comment]
@yunjunz Yes, the notebook changes were included in a later PR that was already merged. I did not use branches correctly.

**Comment by yunjunz** [comment]
So shall we close this PR or merge it?

**Comment by EJFielding** [comment]
I think the `.gitignore` change is still worth merging.

**Review by yunjunz — APPROVED** [review]

**Pull request merged**
