### PR TITLE
update README for UNAVCO2022

### PR DESCRIPTION
**Pull request by nabolfat**
README files in all directories updated.
list of changes:
- year '2021' --> year '2022'
- instructors and TA names updated
- ISCE and MintPy versions updated to ISCE v2.6 and MintPy v1.4.0
- few other details added as needed to some of the README files

### CODE REVIEW

**Comment by yunjunz** [comment]
@fjmeyer Is Forrest an instructor or TA this year? I am confused.

**Comment by EJFielding** [comment]
I thought Forrest was a TA. I put him as TA in the Readme that I edited in #20

**Comment by nabolfat** [comment]
I updated the instructor and TA names based on this link: [https://www.unavco.org/event/2022-short-course-insar-processing-analysis-isce/](url)
I just noticed that the list in the draft doc file is different. Forrest William is TA and Alex Lewandowski is not included in the instructors. @fjmeyer can you please confirm both and I will go ahead and update. 
@yunjunz @EJFielding would you also check if the version of the ISCE and MintPy needs to be updated.

**Comment by yunjunz** [comment]
> @yunjunz @EJFielding would you also check if the version of the ISCE and MintPy needs to be updated.

Yes, the mintpy version of 1.4.0 is correct. Thank you @nabolfat.

**Review by EJFielding — APPROVED** [review]

**Comment by fjmeyer** [comment]
He’s going to attend morning office hours and supports ta work. He’s not charged as an instructor quite yet unless we have a specific need.

**Pull request merged**
