### PR TITLE
Fixes to pre-course to mitigate missing files

### PR DESCRIPTION
**Pull request by geniusinaction**

### CODE REVIEW

**Review by EJFielding — CHANGES_REQUESTED** [review]
It looks like this notebook is still set to "unavco" environment.
```
EarthScope2023/3.1_Preparing_InSAR_data_for_modeling/tensile/okapy_optimization_dike.ipynb
```

**Comment by geniusinaction** [comment]
Not a fatal error, surely? You can always change the environment
when running it?

I don't know how to fix that without doing all this git nonsense again.

Gareth

--
Gareth J Funning (he/him), Professor and Undergraduate Advisor
Department of Earth and Planetary Sciences, University of California,
Riverside, CA 92521, http://www.garethfunning.com/
<http://faculty.ucr.edu/~gareth>

**Comment by EJFielding** [comment]
One other thing is that your pull request seems to have things that you changed before. Can you go to your fork on GitHub and tell it too update it from the original one more time?

**Comment by geniusinaction** [comment]
I've updated my fork with updates from Paul's repo. But I have no idea how
to get rid of the old requests. I am by no means a git expert. Any
suggestions?


Gareth

--
Gareth J Funning (he/him), Professor and Undergraduate Advisor
Department of Earth and Planetary Sciences, University of California,
Riverside, CA 92521, http://www.garethfunning.com/
<http://faculty.ucr.edu/~gareth>

**Review by EJFielding — APPROVED** [review]

**Comment by EJFielding** [comment]
I think the "squash and merge" operation here gets rid of duplicate commits. Yunjun mentioned something about that. I went ahead and did the merge.

**Pull request merged**
