### PR TITLE
Revert "fixed a formula in azimuth compression"

### PR DESCRIPTION
**Pull request by yunjunz**
This reverts commit 9b8ed0a3cccf632407ea4b1fb6c7faaf48d3e76d.

### CODE REVIEW

**Review by EJFielding — APPROVED** [review]

**Comment by EJFielding** [comment]
@yunjunz Somehow, after I merged this revert PR, the notebook is not readable, as pointed out in #57.

**Comment by yunjunz** [comment]
> @yunjunz Somehow, after I merged this revert PR, the notebook is not readable, as pointed out in #57.

It renders fine on my phone for the upstream version. 

image

**Comment by EJFielding** [comment]
Hmm. Depending on how I get to the notebook, it either renders or doesn't. Renders in Chrome now when I got to that file in GitHub.

**Comment by EJFielding** [comment]
The notebook also opens without problems in the UNAVCO2022 OpenSARLabs instance.

**Comment by parosen** [comment]
UNAVCO2021 doesn't render for me, but UNAVCO2022 does render.  We should probably make it so they both render on all browsers.  Sorry - not sure how I screwed this up so badly.  But I'll be sure to use a fork from now on.

**Comment by parosen** [comment]
To avoid a similar screw-up for further changes, I tried to create a fork, but since I'm the owner of GeoSInC, it won't let me create a fork under parosen.  It will let me create one in other places, like isce-framework, but I am reluctant to do that.  Does this mean I have to create a different account so I can create a fork?

**Comment by hfattahi** [comment]
I think you can create a branch on this repo and issue a PR from that branch to your main branch.

**Comment by EJFielding** [comment]
For this purpose, a branch is something like a fork as it keeps the changes separated.

**Comment by parosen** [comment]
OK, now I have to figure out how to branch!

**Pull request merged**
